# Node.js

# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

#TODO: remove this so it triggers on all branches
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.7'
    addToPath: true
    architecture: 'x64'

- script: |
      python -m pip install --upgrade pip 
      pip3 install --upgrade setuptools
      pip3 install -e .[dev]
  displayName: 'Upgrade pip and python'
  continueOnError: false

- script: |
      pip3 install pytest pytest-runner
      pip3 install requests
      sudo apt-get install build-essential chrpath libssl-dev libxft-dev
      sudo apt-get install libfreetype6 libfreetype6-dev libfontconfig1 libfontconfig1-dev
      wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
      tar xvjf phantomjs-2.1.1-linux-x86_64.tar.bz2 -C /usr/local/share/
      sudo ln -sf /usr/local/share/phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/local/bin
  displayName: 'Install test dependencies'
  continueOnError: false

# Run Tests
- script: |
      python -m notebook.jstest 
  displayName: 'Run tests'
  continueOnError: false

# Print test results
# - task: PublishTestResults@2
#   inputs:
#     testResultsFiles: 'result.xml'
#     testRunTitle: 'Python Tests'
#     condition: succeededOrFailed()